src/Entity/Opinions.php
<?php

namespace App\Entity;

use App\Repository\OpinionsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OpinionsRepository::class)
 */
class Opinions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentary;

    /**
     * @ORM\Column(type="integer")
     */
    private $stars;

    /**
     * @ORM\Column(type="date")
     */
    private $publication_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="opinion")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=Movies::class, inversedBy="opinion")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $movies;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="opinion")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentary(): ?string
    {
        return $this->commentary;
    }

    public function setCommentary(?string $commentary): self
    {
        $this->commentary = $commentary;

        return $this;
    }

    public function getStars(): ?int
    {
        return $this->stars;
    }

    public function setStars(int $stars): self
    {
        $this->stars = $stars;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): self
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(?User $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function getMovies(): ?Movies
    {
        return $this->movies;
    }

    public function setMovies(?Movies $movies): self
    {
        $this->movies = $movies;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function __toString() :string {
        return $this->commentary;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Opinions::class, mappedBy="user")
     */
    private $opinion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $userName;

    public function __construct()
    {
        $this->opinion = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Opinions>
     */
    public function getOpinion(): Collection
    {
        return $this->opinion;
    }

    public function addOpinion(Opinions $opinion): self
    {
        if (!$this->opinion->contains($opinion)) {
            $this->opinion[] = $opinion;
            $opinion->setUser($this);
        }

        return $this;
    }

    public function removeOpinion(Opinions $opinion): self
    {
        if ($this->opinion->removeElement($opinion)) {
            // set the owning side to null (unless already changed)
            if ($opinion->getUser() === $this) {
                $opinion->setUser(null);
            }
        }

        return $this;
    }

    public function __toString() :string {
        return $this->email;
    }

    public function setUserName(string $userName): self
    {
        $this->userName = $userName;

        return $this;
    }
}

src/Form/MoviesType.php
<?php

namespace App\Form;

use App\Entity\Movies;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class MoviesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                'label' => 'Nom du film',
                'attr' => [
                    'placeholder' => 'Nom du film',
                ],
            ])
            ->add('releaseDate',DateType::Class, array(
                'widget' => 'choice',
                'years' => range(date('Y'), date('Y')-100),
                'months' => range(1, 12),
                'days' => range(1, 31),
                'label' => 'Date de sortie',
                'attr' => [
                    'placeholder' => 'Date de sortie',
                ],
            ))
            ->add('synopsis', null, [
                'label' => 'Synopsis',
                'attr' => [
                    'placeholder' => 'Synopsis',
                ],
            ])
            ->add('duration', null, [
                'label' => 'Durée',
                'attr' => [
                    'placeholder' => 'Durée',
                ],
            ])
            ->add('picture', FileType::class, [
                'label' => 'Image de couverture',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new Image([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpg',
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Le format de l\'image doit être soit : png, jpg ou jpeg',
                    ])
                ],
            ])
            ->add('category', null, [
                'label' => 'Catégorie',
                'attr' => [
                    'placeholder' => 'Catégorie',
                ],
            ])
            ->add('actors', null, [
                'label' => 'Acteurs',
                'attr' => [
                    'placeholder' => 'Acteurs',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Movies::class,
        ]);
    }
}

src/Controller/MoviesController.php
<?php

namespace App\Controller;

use App\Entity\Movies;
use App\Form\MoviesType;
use App\Repository\MoviesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/movies")
 */
class MoviesController extends AbstractController
{
    /**
     * @Route("/", name="app_movies_index", methods={"GET"})
     */
    public function index(MoviesRepository $moviesRepository): Response
    {
        return $this->render('movies/index.html.twig', [
            'movies' => $moviesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_movies_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $movie = new Movies();
        $form = $this->createForm(MoviesType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form->get('picture')->getData();
            var_dump($uploadedFile);

            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir').'/public/uploads';
                $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$uploadedFile->guessExtension();

                try {
                    $uploadedFile->move(
                        $destination,
                        $newFilename
                    );
                } catch (FileException $e) {
                    var_dump('erreur');
                    var_dump($e);
                }
                $movie->setPicture($newFilename);
            }

                $entityManager->persist($movie);

                $entityManager->flush();

                return $this->redirectToRoute('app_movies_index', [], Response::HTTP_SEE_OTHER);
            }

        return $this->renderForm('movies/new.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_movies_show", methods={"GET"})
     */
    public function show(Movies $movie): Response
    {
        return $this->render('movies/show.html.twig', [
            'movie' => $movie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_movies_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Movies $movie, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $form = $this->createForm(MoviesType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_movies_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('movies/edit.html.twig', [
            'movie' => $movie,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_movies_delete", methods={"POST"})
     */
    public function delete(Request $request, Movies $movie, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->isCsrfTokenValid('delete'.$movie->getId(), $request->request->get('_token'))) {
            $entityManager->remove($movie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_movies_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/movies/_delete_form.html.twig
<form method="post" action="{{ path('app_movies_delete', {'id': movie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ movie.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/movies/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="justify-content-center">
        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/movies/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Movies{% endblock %}

{% block body %}
    <h1>Edit Movies</h1>

    {{ include('movies/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_movies_index') }}">Retour à la liste</a>

    {{ include('movies/_delete_form.html.twig') }}
{% endblock %}

templates/movies/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movies index
{% endblock %}

{% block body %}
	<h1 class="row d-flex justify-content-center mt-5">Tous les films</h1>

{#	<div class="row d-flex  ">#}
		<a href="{{ path('app_movies_new') }}" class="btn btn-primary mb-2">Ajouter</a>
{#	</div>#}

	<div class="row g-2">
		{% for movie in movies %}
			<div class="col-m" style="max-width: 200px">
				<div class="card">
					<img src="{{ asset(image_dir ~ movie.picture) }}" class="card-img-top" alt="image de {{ movie.name }}" style="height: 200px">
					<div class="card-body">
						<h5 class="card-title">{{ movie.name }}</h5>
						<h5 class="card-text">{{ movie.releaseDate ? movie.releaseDate|date('Y-m-d') : '' }}</h5>
						<p class="card-text">{{ movie.synopsis }}</p>
						<p class="card-text">{{ movie.duration }}h</p>
						<a href="{{ path('app_movies_show', {'id': movie.id}) }}">Détails</a>
						{% if is_granted('ROLE_ADMIN') %}
							<a href="{{ path('app_movies_edit', {'id': movie.id}) }}">Modifier</a>
						{% endif %}
					</div>
				</div>
			</div>
		{% else %}
			<div>
				<p>no records found</p>
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/movies/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Movies{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        <h1 class="">Ajouter un nouveau film</h1>
    </div>

    {{ include('movies/_form.html.twig') }}

    <a href="{{ path('app_movies_index') }}">Retourner à la liste</a>
{% endblock %}

templates/movies/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Movies{% endblock %}

{% block body %}
    <a href="{{ path('app_movies_index') }}">Retour à la liste des films</a>

    <div class="d-flex justify-content-center">
        <h1>{{ movie.name }}</h1>
    </div>

    <div class="row">
        <div class="col-4">
            <img src="{{ asset(image_dir ~ movie.picture) }}" alt="image de {{ movie.name }}" style="width: 300px">
        </div>

        <div class="col-8">
            <p>Date de sortie : {{ movie.releaseDate ? movie.releaseDate|date('Y-m-d') : '' }}</p>

            <p>Synopsis :</p>
            <p>{{ movie.synopsis }}</p>

            <p>Durée : {{ movie.duration }}h</p>

            <div class="d-flex justify-content-start">
                <p class="me-1">Avec : </p>
                {% for movie in movie.getActors() %}
                    <p> {{ movie.name }}</p>
                {% endfor %}
            </div>

            <div class="d-flex justify-content-start">
                <p class="me-1">Genre : </p>
                {% for movie in movie.getCategory() %}
                    {{ movie.name }}
                {% endfor %}
            </div>
        </div>
    </div>

    <a href="{{ path('app_opinions_new') }}" class="btn btn-primary">Ajouter un avis</a>

    <div class="mt-4">
        <div class="d-flex justify-content-center">
            <h3>Les Avis</h3>
        </div>
        <div class="row g-2">
            {% for opinion in movie.getOpinion() %}
{#            <div class="border p-3">#}
            <div class="col-m" style="max-width: 200px">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">{{ opinion.commentary }}</p>
                        <p class="card-text">{{ opinion.stars }}</p>
                        <p class="card-text">{{ opinion.publicationDate ? opinion.publicationDate|date('Y-m-d') : '' }}</p>
                        <p class="card-text">{{ opinion.user.username }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div>

        {% if is_granted('ROLE_ADMIN') %}
            <div class="d-flex justify-content-between mt-3">
                <a href="{{ path('app_movies_edit', {'id': movie.id}) }}" class="btn btn-warning">Modifier</a>
                {{ include('movies/_delete_form.html.twig') }}
            </div>
        {% endif %}

    </div>

{% endblock %}